#!/usr/bin/env python3
"""Compile the portrait into `sprite_data.py`, a palette-indexed pixel grid.

    python3 scripts/gen-sprite.py <portrait.png> [size]

One-off; needs Pillow. The card generator only imports the frozen module.

The portrait is a round avatar with a drawn ring. The ring is fitted and the
crop taken just inside it, so the sprite is the artwork itself and not the
ring. Two things keep the likeness at 96 px:

* min-pooling — the darkest sample in each block is blended over the plain
  average, so lash, hair-strand and eye lines survive the downscale instead
  of smearing into skin;
* a fixed palette — the page's own tokens plus the portrait's skin, blush and
  iris, so the sprite and the UI are literally the same colours.
"""

import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageEnhance

HERE = Path(__file__).resolve().parent
OUT = HERE / "sprite_data.py"

# Ring fit on the 460 px source (least squares over the outermost dark pixels).
CENTRE = (229, 230)
RADIUS = 199  # inside the drawn ring

BLOCK = 8
MIN_WEIGHT = 0.42

PALETTE = [
    ("milk", (255, 247, 239)),
    ("cream", (247, 232, 216)),
    ("hair", (241, 224, 208)),
    ("latte", (217, 194, 173)),
    ("taupe", (179, 154, 137)),
    ("cocoa", (138, 106, 85)),
    ("ink", (74, 52, 39)),
    ("skin", (254, 236, 224)),
    ("blush", (250, 214, 196)),
    ("rose", (236, 170, 160)),
    ("amber", (219, 168, 95)),
    ("honey", (240, 207, 143)),
    ("white", (255, 255, 255)),
]

LANCZOS = Image.Resampling.LANCZOS
BOX = Image.Resampling.BOX


def block_min(img: Image.Image, f: int) -> Image.Image:
    w, h = img.size
    out = img.crop((0, 0, w - f + 1, h - f + 1))
    for dy in range(f):
        for dx in range(f):
            if dx == 0 and dy == 0:
                continue
            out = ImageChops.darker(
                out, img.crop((dx, dy, dx + w - f + 1, dy + h - f + 1))
            )
    return out


def pooled(im: Image.Image, size: int) -> Image.Image:
    big = im.resize((size * BLOCK, size * BLOCK), LANCZOS)
    avg = big.resize((size, size), BOX)
    mn = block_min(big, BLOCK).resize((size, size), BOX)
    return Image.blend(avg, mn, MIN_WEIGHT)


def quantise(im: Image.Image) -> Image.Image:
    pal = Image.new("P", (1, 1))
    flat = [v for _, c in PALETTE for v in c]
    pal.putpalette(flat + [0] * (768 - len(flat)))
    return im.quantize(palette=pal, dither=Image.Dither.NONE)


def main() -> int:
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    src = Image.open(sys.argv[1]).convert("RGB")
    size = int(sys.argv[2]) if len(sys.argv) > 2 else 96

    cx, cy = CENTRE
    crop = src.crop((cx - RADIUS, cy - RADIUS, cx + RADIUS, cy + RADIUS))
    small = pooled(crop, size)
    small = ImageEnhance.Color(small).enhance(1.35)
    indices = quantise(small).tobytes()

    rows = []
    half = size / 2
    for y in range(size):
        row = []
        for x in range(size):
            inside = (x + 0.5 - half) ** 2 + (y + 0.5 - half) ** 2 <= half * half
            row.append(f"{indices[y * size + x]:x}" if inside else ".")
        rows.append("".join(row))

    lines = [
        f'"""Compiled pixel portrait: palette indices on a {size} px grid.',
        "",
        "Generated by `scripts/gen-sprite.py`; do not edit by hand.",
        '"""',
        "",
        f"SIZE = {size}",
        "",
        "PALETTE = (",
    ]
    for name, (r, g, b) in PALETTE:
        lines.append(f'    "#{r:02x}{g:02x}{b:02x}",  # {name}')
    lines.append(")")
    lines.append("")
    lines.append("ROWS = (")
    for row in rows:
        lines.append(f'    "{row}",')
    lines.append(")")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    used = sorted({c for row in rows for c in row if c != "."})
    print(f"wrote {OUT.name}: {size}x{size}, {len(used)} colours used")
    return 0


if __name__ == "__main__":
    sys.exit(main())
